// Code generated by goctl. DO NOT EDIT.
package types

type ImgReq struct {
	VehicleNum   string `json:"vehicleNum,optional"`
	GenerateTime string `json:"generateTime,optional"`
	Channel      string `json:"channel,optional"`
	ChassisPhoto string `json:"chassisPhoto,optional"`
	VehiclePhoto string `json:"vehiclePhoto,optional"`
}

type ImgRes struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
