// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"picture/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/car/img",
				Handler: ReceiveImgHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"), rest.WithTimeout(300000*time.Millisecond),
	)
}
